// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8S6VKpQ3zpnkgnja2Eus0Rut_vThtrX4',
    appId: '1:899046507034:ios:6b04f3b09bd7b155bd87a3',
    messagingSenderId: '899046507034',
    projectId: 'arg-restoration',
    storageBucket: 'arg-restoration.firebasestorage.app',
    androidClientId: '899046507034-3tdlp1qp2mjlg14q9sqnmd40lbun12r2.apps.googleusercontent.com',
    iosClientId: '899046507034-8rpiq4vm4upce33oghplvofd476bo6m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobber',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ltksKExNAVMmZ2oWW1pR0KF19L0Y0U8',
    appId: '1:899046507034:android:7782763b2488c6fdbd87a3',
    messagingSenderId: '899046507034',
    projectId: 'arg-restoration',
    storageBucket: 'arg-restoration.firebasestorage.app',
  );

}