// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8S6VKpQ3zpnkgnja2Eus0Rut_vThtrX4',
    appId: '1:899046507034:ios:c143a382087e83e1bd87a3',
    messagingSenderId: '899046507034',
    projectId: 'arg-restoration',
    storageBucket: 'arg-restoration.firebasestorage.app',
    androidClientId: '899046507034-3tdlp1qp2mjlg14q9sqnmd40lbun12r2.apps.googleusercontent.com',
    iosClientId: '899046507034-87o1a2mk2qsmrguuba7sbtueb7b2qckd.apps.googleusercontent.com',
    iosBundleId: 'com.arg.restoration.construction',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ltksKExNAVMmZ2oWW1pR0KF19L0Y0U8',
    appId: '1:899046507034:android:20a65207eb1b5940bd87a3',
    messagingSenderId: '899046507034',
    projectId: 'arg-restoration',
    storageBucket: 'arg-restoration.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrOsAa1YC_oUEwftyPlYhR5xqZJiArX1Y',
    appId: '1:899046507034:web:7d19a9ec40970ca9bd87a3',
    messagingSenderId: '899046507034',
    projectId: 'arg-restoration',
    authDomain: 'arg-restoration.firebaseapp.com',
    storageBucket: 'arg-restoration.firebasestorage.app',
    measurementId: 'G-KZTKS2GZJB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8S6VKpQ3zpnkgnja2Eus0Rut_vThtrX4',
    appId: '1:899046507034:ios:c143a382087e83e1bd87a3',
    messagingSenderId: '899046507034',
    projectId: 'arg-restoration',
    storageBucket: 'arg-restoration.firebasestorage.app',
    androidClientId: '899046507034-3tdlp1qp2mjlg14q9sqnmd40lbun12r2.apps.googleusercontent.com',
    iosClientId: '899046507034-87o1a2mk2qsmrguuba7sbtueb7b2qckd.apps.googleusercontent.com',
    iosBundleId: 'com.arg.restoration.construction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrOsAa1YC_oUEwftyPlYhR5xqZJiArX1Y',
    appId: '1:899046507034:web:4dd3599b676c7dd4bd87a3',
    messagingSenderId: '899046507034',
    projectId: 'arg-restoration',
    authDomain: 'arg-restoration.firebaseapp.com',
    storageBucket: 'arg-restoration.firebasestorage.app',
    measurementId: 'G-1JX69SX4Z1',
  );

}